name: Angular Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./New-portfolio

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      # Install Google Chrome for headless testing
      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb
          sudo apt-get -f install -y

      - name: Set Chrome to run with --no-sandbox
        run: npx ng test --watch=false --browsers=ChromeHeadless
        working-directory: ./New-portfolio

      - name: Build project
        run: npx ng build --prod
        working-directory: ./New-portfolio
