name: Angular Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.0

      - name: Set up Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./Laptop-FrontEnd

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Set Chrome to run with --no-sandbox
        run: export CHROME_BIN=google-chrome-stable && npx ng test --watch=false --browsers=ChromeHeadless
        working-directory: ./portfolio

      - name: Build project
        run: npx ng build --prod
        working-directory: ./portfolio

